GROMACS_OpenMP_testA:
  nsteps: 10000
  rounds: 2
GROMACS_MPI_testA:
  nsteps: 10000
  rounds: 2
R_GFA:
  xsize: 1000
  ysize: 1000
  njobs: 120
  nlearn: 1000
  rounds: 2
CP2K_MPI_testA:
  rounds: 1
